export default [
  "### Limitation des thérapeutiques",
  " - [ ]  Pas de réanimation de l'ACR",
  " - [ ]  Pas de traitement de nouvelles défaillances ou escalade thérapeutique :",
  "   - [ ]  Pas de catécholamines",
  "   - [ ]  Pas d'intubation",
  "   - [ ]  Pas de VNI",
  "   - [ ]  Pas d’O2",
  "   - [ ]  Pas d'EER",
  "   - [ ]  Pas de transfusion ",
  "   - [ ]  Pas de chirurgie",
  "   - [ ]  Pas de PIC ou de DVE",
  "   - [ ]  Pas de nouvelle antibiothérapie",
  "   - [ ]  Pas de ré-intervention chirurgicale",
  "   - [ ]  Pas de nouveaux examens complémentaires",
  "   - [ ]  Pas de bilan biologique",
  "",
  "### Arrêt des thérapeutiques",
  " - [ ]  Arrêt des amines vasopressives",
  " - [ ]  Arrêt de l’épuration extra-rénale",
  " - [ ]  Mise en FIO2  = 21%",
  " - [ ]  Arrêt de l’oxygénothérapie",
  " - [ ]  Arrêt de la ventilation mécanique",
  " - [ ]  Extubation ",
  " - [ ]  Arrêt de la nutrition ",
  " - [ ]  Arrêt de l’hydratation",
  " - [ ]  Arrêt des antibiotiques",
  " - [ ]  Ablation de la DVE",
  " - [ ]  Arrêt de l’ECMO",
  " - [ ]  Arrêt de toutes les thérapeutiques en cours",
  " - [ ]  Autres :",
  "",
  "###  Limitation des thérapeutiques en cours",
  " - [ ]  FiO2 limitée à :      ",
  " - [ ]  Pas de majoration de la VM (NO, DV,…)",
  " - [ ]  Amines limitées à :",
  "",
  "###  Admission en réanimation",
  " - [ ]  Pas de (ré) admission en réanimation",
  "",
  "Date d’application de la décision :",
  "",
  "Commentaires / évolution :",
].join("\n");
